spring:
  application:
    name: keeneye
  datasource:
    url: jdbc:postgresql://localhost:5432/${spring.application.name}
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create